name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '10.0.x'
        
    - name: Publish .NET Project
      run: dotnet publish InvoiceImportBlazor/InvoiceImportBlazor.csproj -c Release -o release --nologo
      
    - name: Change base-tag in index.html
      run: |
        sed -i 's/<base href="\/" \/>/<base href="\/${{ github.event.repository.name }}\/" \/>/g' release/wwwroot/index.html
        
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: release/wwwroot

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
